from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"

HOME_TEAM = "home"
AWAY_TEAM = "away"

INITIAL_PLAYERS = 11

MATCH_START_MINUTE = 1
MATCH_END_MINUTE = 90
MATCH_MAX_MINUTE_ITER = 97

DEFAULT_BIN = 2
DEFAULT_N_CONTROLS = 5

MIN_ANALYSIS_MINUTE = 15
MAX_ANALYSIS_WINDOW = 15

CONTROL_RANDOM_SEED = 42

GOLEADA_THRESHOLD = 3

VAR_GROUP = "VAR"
CONTROL_GROUP = "CONTROL"

STATE_WINNING = "winning"
STATE_DRAWING = "drawing"
STATE_LOSING = "losing"

GOAL_EVENT = "Goal"
PENALTI_GOAL_EVENT = "Goal from penalty"
OWN_GOAL_EVENT = "Own goal"
YELLOW_CARD_EVENT = "Yellow card"
RED_CARD_EVENT = "Red card"
SECOND_YELLOW_RED_EVENT = "2nd yellow card leads to red card"
VAR_EVENT_TYPE = "Goal disallowed by VAR"

GOAL_EVENTS = {
    GOAL_EVENT,
    PENALTI_GOAL_EVENT,
    OWN_GOAL_EVENT
}

CARD_EVENTS = {
    YELLOW_CARD_EVENT,
    RED_CARD_EVENT,
    SECOND_YELLOW_RED_EVENT
}

RED_EVENTS = {
    RED_CARD_EVENT,
    SECOND_YELLOW_RED_EVENT
}


